#!/usr/bin/env python3
"""Download production model artifacts from GitHub Release.

Downloads model.onnx, model.lgb, train_medians.npy, and
threshold_biases.npy from the latest GitHub Release into artifacts/.
Required before running the inference pipeline
(``python -m rocket_classifier.main``).

Usage:
    python download_models.py
    # or: make download-models
"""

from __future__ import annotations

import sys
import time
import urllib.error
import urllib.request
from pathlib import Path

# Import the canonical URL from the production package to avoid duplication.
# This script lives outside the package, so we add the project root to sys.path.
sys.path.insert(0, str(Path(__file__).parent.parent))
from rocket_classifier import RELEASE_BASE_URL

RELEASE_BASE = RELEASE_BASE_URL

# Required artifacts — pipeline fails without these.
ARTIFACTS = [
    "model.lgb",
    "train_medians.npy",
    "threshold_biases.npy",
]

# Optional artifacts — downloaded if present in the release; skipped silently if not.
# model.onnx / model_opt.onnx are generated by `make export-model` and may not exist in every release.
# model_opt.onnx is the pre-graph-optimized variant — loads ~0.3s faster than model.onnx.
OPTIONAL_ARTIFACTS = [
    "model_opt.onnx",
    "model.onnx",
]

# Feature caches — parquet files (~5 MB total).
# Optional: skip if you have data/ and want to recompute from scratch.
CACHE_ARTIFACTS = [
    "cache_train_features.parquet",
    "cache_test_features.parquet",
]

# Data artifacts downloaded alongside caches so the pipeline can run without data/.
DATA_ARTIFACTS = [
    "test.csv",
    "sample_submission.csv",
]

ROOT = Path(__file__).parent.parent
ARTIFACTS_DIR = ROOT / "artifacts"
CACHE_DIR = ROOT / "cache"
DATA_DIR = ROOT / "data"
ARTIFACTS_DIR.mkdir(exist_ok=True)
CACHE_DIR.mkdir(exist_ok=True)

_MAX_RETRIES = 3
_RETRY_BACKOFF_S = 2  # seconds; doubles each retry


def _download_with_retry(url: str, dest: Path, *, max_retries: int = _MAX_RETRIES) -> None:
    """Download a file with exponential-backoff retry on transient failures."""
    for attempt in range(1, max_retries + 1):
        try:
            urllib.request.urlretrieve(url, str(dest))
            return
        except (urllib.error.URLError, urllib.error.HTTPError, OSError, TimeoutError):
            if attempt == max_retries:
                raise
            wait = _RETRY_BACKOFF_S * (2 ** (attempt - 1))
            print(f"retry {attempt}/{max_retries} in {wait}s ...", end=" ", flush=True)
            time.sleep(wait)


def main(include_caches: bool = False) -> None:
    """Download model artifacts from GitHub Release into artifacts/ and cache/.

    Args:
        include_caches: If True, also downloads parquet feature caches (~15 MB)
            and sample_submission.csv into data/. Required for ``make run``
            when data/ is not available locally.
    """
    required = ARTIFACTS + (CACHE_ARTIFACTS + DATA_ARTIFACTS if include_caches else [])
    for name in required:
        if name.endswith(".parquet"):
            dest = CACHE_DIR / name
        elif name.endswith(".csv"):
            DATA_DIR.mkdir(exist_ok=True)
            dest = DATA_DIR / name
        else:
            dest = ARTIFACTS_DIR / name
        if dest.exists():
            print(f"  {name} — already exists, skipping")
            continue
        url = f"{RELEASE_BASE}/{name}"
        print(f"  Downloading {name} ...", end=" ", flush=True)
        try:
            _download_with_retry(url, dest)
            size_mb = dest.stat().st_size / 1_048_576
            print(f"OK ({size_mb:.1f} MB)")
        except Exception as exc:
            print(f"FAILED: {exc}")
            sys.exit(1)

    for name in OPTIONAL_ARTIFACTS:
        dest = ARTIFACTS_DIR / name
        if dest.exists():
            print(f"  {name} — already exists, skipping")
            continue
        url = f"{RELEASE_BASE}/{name}"
        print(f"  Downloading {name} ...", end=" ", flush=True)
        try:
            _download_with_retry(url, dest)
            size_mb = dest.stat().st_size / 1_048_576
            print(f"OK ({size_mb:.1f} MB)")
        except Exception:
            print("not in release, skipping (run `make export-model` to generate)")

    print("All artifacts ready.")


if __name__ == "__main__":
    caches = "--with-caches" in sys.argv
    main(include_caches=caches)
